config/routes.rb
Rails.application.routes.draw do

  delete '/sessions' => "sessions#destroy"
  delete '/posts/:id' => "posts#destroy"
  patch '/posts' => "posts#update"
  get '/posts/new' => "posts#new"
  post '/posts' => "posts#create"
  get '/posts/:id' => "posts#show"
  get '/posts/:id/edit' => "posts#edit"
  get '/posts' => "posts#index"
  post '/sessions' => "sessions#create"
  get '/sessions' => "sessions#new"
  post '/users' => 'users#create'
  get '/users/show' => "users#show"
  get '/users/index' => "users#index"
  root "users#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :first_name, :last_name, presence: true
  validates :password, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def current_user
    @logged_in = User.find(session[:user_id]) if session[:user_id]
  end

  def is_logged_in
    return @logged_in if current_user
  end

  helper_method :current_user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = current_user.posts
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to "/posts"
    else
      flash[:notice] = "not working"
      redirect_to "/posts/new"
    end
  end

  def update
    set_post.update(post_params)
    redirect_to '/posts', notice: "Post was updated!!"
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    set_post.destroy
    redirect_to '/posts', notice: "Post was deleted!"
  end

  private
  def post_params
    params.require(:post).permit(:title, :description)
  end

  def set_post
    Post.find_by(params[:post_id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(session_params[:email])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
  		redirect_to '/posts'
    else
      flash[:error] = "There was an error logging in"
      redirect_to '/'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  private
    def session_params
      params.require(:sessions).permit(:email, :password)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = User.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        redirect_to '/posts'
      else
        flash[:error] = @user.errors.full_messages.to_s
        redirect_to '/'
      end
  end

  def show
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginRegistrationRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <% if current_user %>
      <p>Hi <%= current_user.first_name %>!</p>
      <%= link_to "Home", "/posts" %> |
      <%= link_to "Logout", '/sessions', method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, url: posts_path do |f| %>
  <%= f.label "Title" %> <%= f.text_field :title %>
  <%= f.label "Description" %> <%= f.text_field :description %>
  <%= f.button :submit%>
  <% end %>

app/views/posts/index.html.erb
<p style="color: green;"><%= notice %></p>

<%= link_to "Create a new post", "/posts/new"%>
<hr />

<h2>All Posts</h2>
<br />
<% @posts.each do |post| %>

  <h4><%= post.title %></h4>
  <h6>This is post # <%= post.id %></h6>
  <%= post.description %>
  <p><%= link_to "Edit", '/posts/:id' %> |
     <%= link_to 'Delete', '/posts/:id', method: :delete, data: {confirm: "Are you sure?"} %>
<hr>
<% end %>

app/views/posts/new.html.erb
<h3>Create a new Post</h3>
<%= flash[:notice] %>

<%= render 'form' %>

app/views/posts/show.html.erb
<h1> Update your post! </h1>

<%= render 'form' %>

app/views/users/_form.html.erb
<%= form_for @user, url: users_path do |f| %>
  <%= f.label "First Name" %> <%= f.text_field :first_name %>
  <%= f.label "Last Name" %> <%= f.text_field :last_name %>
  <%= f.label "Email Address" %> <%= f.text_field :email %>
  <%= f.label "Password" %> <%= f.text_field :password %>
  <%= f.button :submit %>

<% end %>

app/views/users/index.html.erb
<% flash.each do |key, value| %>
  <p style="color: red;"><%= value %></p>
      <% end %>


<h3>Login and Registration with Rails </h3>
<%= render 'form' %>
<br />
<br />
<p>
  Already registered?
</p>
<%= link_to "Login", "/sessions" %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>